import React, { useState } from 'react';

const AddPenggunaForm = ({ onClose, onAdd }) => {
    const [formData, setFormData] = useState({
        username: '',
        email: '',
        phone: '',
        status: 'Aktif',
    });

    // Handle form input change
    const handleChange = (e) => {
        const { name, value } = e.target;
        setFormData(prevState => ({
            ...prevState,
            [name]: value
        }));
    };

    // Handle form submit
    const handleSubmit = (e) => {
        e.preventDefault();

        // Create new pengguna object
        const newPengguna = {
            id: Date.now(), // Using timestamp as a unique ID (in a real-world scenario, this should be generated by the backend)
            ...formData
        };

        onAdd(newPengguna); // Add the new pengguna to the list
        onClose(); // Close the modal after adding
    };

    return (
        <div className="modal-overlay">
            <div className="modal-content">
                <h3>Tambah Pengguna Baru</h3>
                <form onSubmit={handleSubmit}>
                    <div className="form-group">
                        <label>Username</label>
                        <input
                            type="text"
                            name="username"
                            value={formData.username}
                            onChange={handleChange}
                            required
                        />
                    </div>
                    <div className="form-group">
                        <label>Email</label>
                        <input
                            type="email"
                            name="email"
                            value={formData.email}
                            onChange={handleChange}
                            required
                        />
                    </div>
                    <div className="form-group">
                        <label>No Tlp</label>
                        <input
                            type="text"
                            name="phone"
                            value={formData.phone}
                            onChange={handleChange}
                            required
                        />
                    </div>
                    <div className="form-group">
                        <label>Status</label>
                        <select
                            name="status"
                            value={formData.status}
                            onChange={handleChange}
                            required
                        >
                            <option value="Aktif">Aktif</option>
                            <option value="Nonaktif">Nonaktif</option>
                        </select>
                    </div>
                    <div className="form-actions">
                        <button type="submit" className="submit-button">Tambah</button>
                        <button type="button" onClick={onClose} className="cancel-button">Batal</button>
                    </div>
                </form>
            </div>
        </div>
    );
};

export default AddPenggunaForm;
